export const roles = {
  manager: {
    label: 'Manager',
    name: 'Program Manager',
    description: 'Full workspace access',
    initials: 'PM',
  },
  employee: {
    label: 'Employee',
    name: 'Software / IT Intern',
    description: 'Assigned work and requests',
    initials: 'IT',
  },
  finance: {
    label: 'Finance',
    name: 'Finance Officer',
    description: 'Budgets, requests, payments',
    initials: 'FO',
  },
};

export const navigation = {
  manager: [
    ['dashboard', 'Dashboard'],
    ['projects', 'Projects'],
    ['requisitions', 'Requisitions'],
    ['tasks', 'Task Board'],
    ['reports', 'Reports'],
  ],
  employee: [
    ['my-dashboard', 'My Dashboard'],
    ['my-tasks', 'My Tasks'],
    ['my-requests', 'My Requests'],
    ['work-log', 'Work Log'],
  ],
  finance: [
    ['finance-dashboard', 'Finance Dashboard'],
    ['finance-requests', 'Request Review'],
    ['payments', 'Payments'],
    ['budget', 'Budget'],
  ],
};

export const projects = [
  {
    id: 1,
    name: 'Digital Service Platform',
    program: 'Digital Innovation',
    projectCode: 'PRJ-DIG-001',
    budgetLine: 'Digital systems',
    activity: 'Platform improvement',
    items: 'Hosting, design, database',
    owner: 'Program Manager',
    status: 'Active',
    budget: 1200000,
    spent: 980000,
    start: '2026-01-10',
    end: '2026-09-30',
    progress: 78,
    description:
      'A web-based platform for service information, internal tracking, and digital tools for field support teams.',
  },
  {
    id: 2,
    name: 'Program Data Dashboard',
    program: 'Research',
    projectCode: 'PRJ-DATA-002',
    budgetLine: 'Monitoring and evaluation',
    activity: 'Dashboard setup',
    items: 'Forms, indicators, reports',
    owner: 'Data Officer',
    status: 'Active',
    budget: 850000,
    spent: 520000,
    start: '2026-02-01',
    end: '2026-08-15',
    progress: 58,
    description:
      'Monitoring and evaluation dashboard connecting data collection to real-time reporting for managers and partners.',
  },
  {
    id: 3,
    name: 'Community Outreach Tool',
    program: 'Digital Innovation',
    projectCode: 'PRJ-OUT-003',
    budgetLine: 'Project activities',
    activity: 'Outreach tracking',
    items: 'Mobile forms, referral logs',
    owner: 'Software / IT Intern',
    status: 'Planning',
    budget: 600000,
    spent: 120000,
    start: '2026-04-01',
    end: '2026-12-31',
    progress: 25,
    description:
      'Mobile-friendly tool for tracking outreach visits, referrals, and follow-ups in low-connectivity settings.',
  },
];

export const tasks = [
  {
    id: 1,
    title: 'Design request form flow',
    projectId: 1,
    assignee: 'Software / IT Intern',
    status: 'Done',
    priority: 'High',
    due: '2026-06-08',
  },
  {
    id: 2,
    title: 'Build requisition data model',
    projectId: 1,
    assignee: 'Software / IT Intern',
    status: 'In Progress',
    priority: 'High',
    due: '2026-06-12',
  },
  {
    id: 3,
    title: 'Review dashboard indicators',
    projectId: 2,
    assignee: 'Data Officer',
    status: 'In Progress',
    priority: 'Medium',
    due: '2026-06-14',
  },
  {
    id: 4,
    title: 'Prepare staff training notes',
    projectId: 3,
    assignee: 'M&E Officer',
    status: 'Review',
    priority: 'Medium',
    due: '2026-06-15',
  },
];

export const requisitions = [
  {
    id: 1,
    requestNo: 'REQ-OPS-001',
    date: '2025-08-04',
    details: 'Purchasing equipment for an internal support role',
    projectCode: 'PRJ-OPS-001',
    budgetLine: 'Organisational costs',
    activity: 'Office equipment support',
    items: 'Computer equipment',
    amount: 650000,
    supportingDocuments: 'Purchase request, quotation, approval memo',
    status: 'Submitted',
    prepared: {
      names: 'Administrative Assistant',
      position: 'Administrative Assistant',
      comments: 'Request prepared with basic details and supporting documents.',
      status: 'Ready for Verification',
    },
    verified: {
      names: 'Finance Officer',
      position: 'Finance Officer',
      comments: 'Supporting documents should be complete before payment.',
      recommendations: 'Attach signed minutes and contract where needed.',
      status: 'Ready for Executive Approval',
    },
    executive: {
      names: 'Executive Director',
      position: 'Executive Director',
      comments: 'Awaiting executive decision.',
      recommendations: '',
      status: 'Pending',
    },
    board: {
      names: 'Board Chair',
      position: 'Chair of the Board',
      comments: 'Check purchase terms and return policy.',
      recommendations: 'Confirm warranty and return terms.',
      status: 'Pending',
    },
    progress: {
      spentAmount: 0,
      referenceNo: 'Pending',
      paymentSupportingDocument: 'Not uploaded',
      variance: 0,
      varianceReason: '',
      varianceExplanation: 'Waiting for final approval',
    },
  },
  {
    id: 2,
    requestNo: 'REQ-ACT-002',
    date: '2025-08-05',
    details: 'Transportation and facilitation support for a coordination team event',
    projectCode: 'PRJ-ACT-002',
    budgetLine: 'Project activities',
    activity: 'Partner launch event',
    items: 'Transportation and facilitation fees',
    amount: 195000,
    supportingDocuments: 'Attendance list, activity budget, payment list',
    status: 'Approved',
    prepared: {
      names: 'Finance Assistant Intern',
      position: 'Finance Assistant Intern',
      comments: 'Request entered with event and participant payment details.',
      status: 'Ready for Verification',
    },
    verified: {
      names: 'Finance Officer',
      position: 'Finance Officer',
      comments: 'Payment source confirmed and request is ready for approval.',
      recommendations: 'Ready for executive approval.',
      status: 'Ready for Executive Approval',
    },
    executive: {
      names: 'Executive Director',
      position: 'Executive Director',
      comments: 'Approved for payment processing.',
      recommendations: '',
      status: 'Approved',
    },
    board: {
      names: 'Board Chair',
      position: 'Chair of the Board',
      comments: 'Approved under planned activity support.',
      recommendations: '',
      status: 'Approved',
    },
    progress: {
      spentAmount: 195000,
      referenceNo: 'PAY-REF-002',
      paymentSupportingDocument: 'Facilitation fees payment.pdf',
      variance: 0,
      varianceReason: 'None',
      varianceExplanation: 'Payment aligned with approved amount',
    },
  },
];

export const paymentList = [
  ['Participant 01', '078 *** 0001', 'Medical Student', 15000, 'Pending'],
  ['Participant 02', '078 *** 0002', 'Medical Student', 15000, 'Pending'],
  ['Participant 03', '078 *** 0003', 'MDFC Staff', 15000, 'Paid'],
  ['Participant 04', '078 *** 0004', 'Photographer', 15000, 'Pending'],
];
